## Parses FIX protocol strings generated by FIX_generator.py
#  See https://ref.onixs.biz/fix-message.html for str documentation

def FIX_parser(msg: str) -> dict:
    delim = "\x01"
    params = msg.split(delim)
    d = {}
    required_tags = [38,55,54]

    for p in params:
        tag,val = p.split('=',1)
        d[int(tag)] = val
    
    for t in required_tags:
        if t not in d:
            raise ValueError(f"Missing Required Parameter: {t}")

    return d

